name: Zip-n-Release
 
on:
  push:
    branches:
      - main
 
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Install zip
        run: sudo apt-get install zip
 
      - name: Create Zip Archive
        run: zip -r GPiCase2Wpatch_retropie_zero2.zip GPiCase2Wpatch_retropie_zero2
 
      - name: Get Release Changelog
        id: changelog
        run: |
          echo "::set-output name=changelog::$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'- %s')"
 
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.sha }}
          name: Release ${{ github.sha }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
 
      - name: Upload Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GPiCase2Wpatch_retropie_zero2.zip
          asset_name: GPiCase2Wpatch_retropie_zero2.zip
          asset_content_type: application/zip
 
